# version of  Docker Compose file
version: "3.8"

services:
  # book_catalog service
  book_cat:
  
    build:

      context: ./book_catalog

      dockerfile: Dockerfile

    ports:
      - "80:80"
    # environment variables for the container
    environment:
      # DATABASE_URL environment variable for the PostgreSQL connection
      - DATABASE_URL=postgresql://book_cat_user:a4DIpcnKXM1ixU77QBXs8l96GxoG8c1z@dpg-crlqm6bv2p9s73e2ss00-a.oregon-postgres.render.com/book_cat

    

  # Define the inventory_management service
  management_invent:
   
    build:
   
      context: ./inventory_management

      dockerfile: Dockerfile
   
    ports:
      - "81:81"
    # Define environment variables for container
    environment:
      - DATABASE_URL=postgresql://book_cat_user:a4DIpcnKXM1ixU77QBXs8l96GxoG8c1z@dpg-crlqm6bv2p9s73e2ss00-a.oregon-postgres.render.com/book_cat
   